//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikitKursa4
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoserviceNikit
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MidleName { get; set; }
        public int RoleId { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int ContractId { get; set; }
    
        public virtual ContractsNikit ContractsNikit { get; set; }
        public virtual RoleNikit RoleNikit { get; set; }
    }
}
