//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikitKursa4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsNikit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractsNikit()
        {
            this.AutoserviceNikit = new HashSet<AutoserviceNikit>();
        }
    
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Number { get; set; }
        public int CompanyId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoserviceNikit> AutoserviceNikit { get; set; }
        public virtual CompanyNikit CompanyNikit { get; set; }
    }
}
